root: true
env:
  node: true
  jest: true
extends:
  - "eslint:recommended"
  - "prettier"
parserOptions:
  ecmaVersion: latest
  sourceType: module
overrides:
  - files: "*.ts"
    parser: "@typescript-eslint/parser"
    extends:
      - "plugin:@typescript-eslint/recommended"
    plugins:
      - "@typescript-eslint"
    parserOptions:
      project: "./tsconfig.json"
      ecmaVersion: latest
      sourceType: module
